### ISSUE TITLE
Advanced Custom Fields PRO

### ISSUE THREAD

**Issue by adulovic** [eduardo-marcolino/acf-fields-in-custom-table#11]
WordPress v5.7.1
Advanced Custom Fields PRO v5.9.5
Advanced Forms v1.8.0
Sample table fields used: text, email, radio button, date time picker

Enabling ACF: Fields in Custom Tables creates a table with the prefix wp_acf_, 
But it does not insert any data sent by the forms.
(Seems like the hook acf/update_field_group is working, but the acf/save_post isn't.)

Is this a know issue with the PRO version?
Am I missing some important step?
How can I debug?

**Comment by eduardo-marcolino** [comment]
I didn't test it with ACF PRO yet.
How are you saving the data? Using the regular wp-admin interface ?

**Comment by adulovic** [comment]
users submitting data through forms on the frontend

**Comment by eduardo-marcolino** [comment]
Oh Right. At this moment the plugin only add a hook to the acf/save_post action.
I don't know if you are using a plugin like ACF Frontend or doing the implementation by yourself but it's probably using the `update_field` function which will not trigger the acf/save_post action.

**Comment by adulovic** [comment]
Am just doing cleanup duty after another programmer, seems like a vanilla install.
Thanks for the tip, I'll look into that and report back if solved (in case anyone else has the same issue).

**Comment by adulovic** [comment]
So, did a quick check and each form has its own submit function and they all use <code>update_field</code>.
As an example, there is a <code>function send_states($parameters) {...}</code>.
I tried adding the line  <code>add_action('acf/save_post', 'send_states');</code> before (and after) the function, but it still won't save into the custom table. I also tried them with priority 5 and priority 20, no luck...
Any suggestions on what else I could try?

**Comment by eduardo-marcolino** [comment]
I didn't test it but i'll do something like add a hook to the [acf/update_value](https://www.advancedcustomfields.com/resources/acf-update_value/) filter. That's triggered right before storing to database.

Then you can check for the table name and if its enabled or not in the `acfict_table_name` and `acfict_enabled` keys from $field parameter.

After that you can update the table using wpdb replace method for example:

```php
<?php

add_filter('acf/update_value', function( $value, $post_id, $field, $original ) 
{
  if ( $field[self::SETTINGS_ENABLED] && $field['name'] ) 
  {
    $column_name = acfict_sanitize_keyword( $field['name'] );
    $column_value = apply_filters( 'acfict_sanitize_'.$field['type'], $value, $field );
    $wpdb->replace(  'wp_acf_'. $field[ACF_FICT::SETTINGS_TABLE_NAME], [ $column_name => $column_value]  );
  }

}, 10, 4);
```

Again, i didn't test it. I hope it can help you. Let me know if it works ;)

**Comment by adulovic** [comment]
Tried your suggestion but it didn't help me much as the previous programmer didn't comment any of his code so it was a struggle to understand his logic. As I was in a hurry, I just created new forms and tables directly and the client is happy with that.
Thanks for the help anyway

**Comment by victoriusnet** [comment]
Hi,

WP 5.7.2 - fresh install
PHP 7.4.1
MariaDB 10.4.10
ACF PRO 5.9.5

Custom Fields menu -> Add new:

![image](https://user-images.githubusercontent.com/48323740/118531976-bc51c000-b746-11eb-9aa8-311551103ec0.png)



Warning: _() expects exactly 1 parameter, 2 given in C:\Users\Viktor\Local Sites\hurghada\app\public\wp-content\plugins\acf-fields-in-custom-table\acf-fields-in-custom-table.php on line&nbsp;108
--

1 | 0.0002 | 368064 | {main}( ) | ...\post.php:0
2 | 2.2539 | 4195264 | require(&nbsp;'C:\Users\Viktor\Local Sites\hurghada\app\public\wp-admin\edit-form-advanced.php'&nbsp;) | ...\post.php:206
3 | 2.3354 | 4367368 | do_meta_boxes( ) | ...\edit-form-advanced.php:688
4 | 2.3577 | 4458240 | ACF_FICT-&gt;render_meta_box( ) | ...\template.php:1389
5 | 2.3650 | 4458368 | _&nbsp;( ) | ...\acf-fields-in-custom-table.php:108
