### ISSUE TITLE
Not working on fresh install

### ISSUE THREAD

**Issue by victoriusnet** [eduardo-marcolino/acf-fields-in-custom-table#12]
Hi,

WP 5.7.2 - fresh install
PHP 7.4.1
MariaDB 10.4.10
ACF PRO 5.9.5

Custom Fields menu -> Add new:

https://user-images.githubusercontent.com/48323740/118531976-bc51c000-b746-11eb-9aa8-311551103ec0.png

Warning: _() expects exactly 1 parameter, 2 given in C:\Users\Viktor\Local Sites\hurghada\app\public\wp-content\plugins\acf-fields-in-custom-table\acf-fields-in-custom-table.php on line 108
1 | 0.0002 | 368064 | {main}( ) | ...\post.php:0
2 | 2.2539 | 4195264 | require( 'C:\Users\Viktor\Local Sites\hurghada\app\public\wp-admin\edit-form-advanced.php' ) | ...\post.php:206
3 | 2.3354 | 4367368 | do_meta_boxes( ) | ...\edit-form-advanced.php:688
4 | 2.3577 | 4458240 | ACF_FICT->render_meta_box( ) | ...\template.php:1389
5 | 2.3650 | 4458368 | _ ( ) | ...\acf-fields-in-custom-table.php:108

Any advice?

**Comment by eduardo-marcolino** [comment]
This issue was fixed on #8
