### ISSUE TITLE
Cannot delete fields in custom table

### ISSUE THREAD

**Issue by dahuangfeng123** [eduardo-marcolino/acf-fields-in-custom-table#13]
Hi guys，Here is some useful information.
WordPress 5.7.2
ACF: Fields in Custom Table Version 0.5
Advanced Custom Fields Version 5.9.6
![11111111](https://user-images.githubusercontent.com/3371478/119756197-c8234c00-bed5-11eb-86a5-d8b15f9671a5.PNG)
![222222222222222222](https://user-images.githubusercontent.com/3371478/119756202-c9547900-bed5-11eb-830a-29154691a6fa.PNG)

**Comment by eduardo-marcolino** [comment]
Hi @dahuangfeng123 .

The plugin uses wordpress core function [dbDelta](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-admin/includes/upgrade.php#L2718).
dbDelta can add or alter columns, but not drop them.

You can implement your own delete routine by hooking into `acf/update_field_group` and use [maybe_drop_column](https://developer.wordpress.org/reference/functions/maybe_drop_column/) function:

```php
add_action( 'acf/update_field_group', function( $field_group ) {

      // Skip if the custom table is not enable
      if ( !$field_group[self::SETTINGS_ENABLED]) {
        return;
      }
    
     $tablename = $field_group[ACF_FICT::SETTINGS_TABLE_NAME];
     // Add your code to drop columns
});
```

**Comment by dahuangfeng123** [comment]
Great!
