### ISSUE TITLE
Forgot to remove **healthcare** post type

### ISSUE THREAD

**Issue by haniefss** [eduardo-marcolino/acf-fields-in-custom-table#2]
Hi Eduardo great work releasing this plugin (the alternative is just way too expensive).

I tried this plugin and found that it registers **healthcare** post type. It's from _includes/acfict-utility-functions.php_ line 78. Perhaps you forgot to remove it?

![image](https://user-images.githubusercontent.com/39113199/102601862-4f180f80-4153-11eb-86c6-15cfe4810c59.png)

**Comment by eduardo-marcolino** [comment]
Hi @haniefss thanks for the bug report!
I just fixed it along with other improvements and relase the 0.4 version.
